name: Rust-docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      run: cargo doc --frozen --release --workspace \
        --exclude pallet-donations \
        --exclude pallet-moderation \
        --exclude pallet-session-keys \
        --exclude pallet-space-multi-ownership \
        --exclude pallet-subscriptions
    - name: Move docs to docs folder
      run: mv target/docs/ ./docs/
